-- Generated from docs/txadmin-routes.json. Do not add arbitrary URL forwarding.
TxBridge.txRoutes = {
    ["adminManager_page"] = { method="GET", path="/legacy/adminManager", auth="webAuthMw", exposure="experimental" },
    ["cfgEditor_page"] = { method="GET", path="/legacy/cfgEditor", auth="webAuthMw", exposure="experimental" },
    ["masterActions_page"] = { method="GET", path="/legacy/masterActions", auth="webAuthMw", exposure="experimental" },
    ["resources"] = { method="GET", path="/legacy/resources", auth="webAuthMw", exposure="experimental" },
    ["serverLog"] = { method="GET", path="/legacy/serverLog", auth="webAuthMw", exposure="experimental" },
    ["whitelist_page"] = { method="GET", path="/legacy/allowlist", auth="webAuthMw", exposure="experimental" },
    ["setup_get"] = { method="GET", path="/legacy/setup", auth="webAuthMw", exposure="experimental" },
    ["deployer_stepper"] = { method="GET", path="/legacy/deployer", auth="webAuthMw", exposure="experimental" },
    ["auth_self"] = { method="GET", path="/auth/self", auth="apiAuthMw", exposure="reference-only: authentication lifecycle" },
    ["auth_verifyPassword"] = { method="POST", path="/auth/password", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_logout"] = { method="POST", path="/auth/logout", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_addMasterPin"] = { method="POST", path="/auth/addMaster/pin", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_addMasterCallback"] = { method="POST", path="/auth/addMaster/callback", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_addMasterSave"] = { method="POST", path="/auth/addMaster/save", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_providerRedirect"] = { method="GET", path="/auth/cfxre/redirect", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_providerCallback"] = { method="POST", path="/auth/cfxre/callback", auth="authLimiter", exposure="reference-only: authentication lifecycle" },
    ["auth_changePassword"] = { method="POST", path="/auth/changePassword", auth="apiAuthMw", exposure="reference-only: authentication lifecycle" },
    ["auth_getIdentifiers"] = { method="GET", path="/auth/getIdentifiers", auth="apiAuthMw", exposure="reference-only: authentication lifecycle" },
    ["auth_changeIdentifiers"] = { method="POST", path="/auth/changeIdentifiers", auth="apiAuthMw", exposure="reference-only: authentication lifecycle" },
    ["adminManager_getModal"] = { method="POST", path="/adminManager/getModal/:modalType", auth="webAuthMw", exposure="experimental" },
    ["adminManager_actions"] = { method="POST", path="/adminManager/:action", auth="apiAuthMw", exposure="experimental" },
    ["setup_post"] = { method="POST", path="/setup/:action", auth="apiAuthMw", exposure="experimental" },
    ["deployer_status"] = { method="GET", path="/deployer/status", auth="apiAuthMw", exposure="experimental" },
    ["deployer_actions"] = { method="POST", path="/deployer/recipe/:action", auth="apiAuthMw", exposure="experimental" },
    ["settings_getConfigs"] = { method="GET", path="/settings/configs", auth="apiAuthMw", exposure="experimental" },
    ["settings_saveConfigs"] = { method="POST", path="/settings/configs/:card", auth="apiAuthMw", exposure="experimental" },
    ["settings_getBanTemplates"] = { method="GET", path="/settings/banTemplates", auth="apiAuthMw", exposure="experimental" },
    ["settings_saveBanTemplates"] = { method="POST", path="/settings/banTemplates", auth="apiAuthMw", exposure="experimental" },
    ["settings_resetServerDataPath"] = { method="POST", path="/settings/resetServerDataPath", auth="apiAuthMw", exposure="experimental" },
    ["masterActions_getBackup"] = { method="GET", path="/masterActions/backupDatabase", auth="webAuthMw", exposure="experimental" },
    ["masterActions_actions"] = { method="POST", path="/masterActions/:action", auth="apiAuthMw", exposure="experimental" },
    ["fxserver_controls"] = { method="POST", path="/fxserver/controls", auth="apiAuthMw", exposure="experimental" },
    ["fxserver_commands"] = { method="POST", path="/fxserver/commands", auth="apiAuthMw", exposure="experimental" },
    ["fxserver_downloadLog"] = { method="GET", path="/fxserver/downloadLog", auth="webAuthMw", exposure="experimental" },
    ["fxserver_schedule"] = { method="POST", path="/fxserver/schedule", auth="apiAuthMw", exposure="experimental" },
    ["cfgEditor_save"] = { method="POST", path="/cfgEditor/save", auth="apiAuthMw", exposure="experimental" },
    ["intercom"] = { method="POST", path="/intercom/:scope", auth="intercomAuthMw", exposure="blocked: private intercom" },
    ["diagnostics_getDiagnostics"] = { method="GET", path="/diagnostics/getDiagnostics", auth="apiAuthMw", exposure="experimental" },
    ["diagnostics_sendReport"] = { method="POST", path="/diagnostics/sendReport", auth="apiAuthMw", exposure="experimental" },
    ["advanced_runCommand"] = { method="POST", path="/advanced/run", auth="apiAuthMw", exposure="experimental" },
    ["serverLogPartial"] = { method="GET", path="/serverLog/partial", auth="apiAuthMw", exposure="experimental" },
    ["systemLogs"] = { method="GET", path="/systemLog/:scope", auth="apiAuthMw", exposure="experimental" },
    ["perfChart"] = { method="GET", path="/perfChartData/:thread", auth="apiAuthMw", exposure="experimental" },
    ["playerDrops"] = { method="GET", path="/playerDropsData", auth="apiAuthMw", exposure="experimental" },
    ["history_stats"] = { method="GET", path="/history/stats", auth="apiAuthMw", exposure="experimental" },
    ["history_search"] = { method="GET", path="/history/search", auth="apiAuthMw", exposure="experimental" },
    ["history_actionModal"] = { method="GET", path="/history/action", auth="apiAuthMw", exposure="experimental" },
    ["history_actions"] = { method="POST", path="/history/:action", auth="apiAuthMw", exposure="experimental" },
    ["player_modal"] = { method="GET", path="/player", auth="apiAuthMw", exposure="experimental" },
    ["player_stats"] = { method="GET", path="/player/stats", auth="apiAuthMw", exposure="experimental" },
    ["player_search"] = { method="GET", path="/player/search", auth="apiAuthMw", exposure="experimental" },
    ["player_checkJoin"] = { method="POST", path="/player/checkJoin", auth="intercomAuthMw", exposure="blocked: private intercom" },
    ["player_actions"] = { method="POST", path="/player/:action", auth="apiAuthMw", exposure="experimental" },
    ["whitelist_list"] = { method="GET", path="/whitelist/:table", auth="apiAuthMw", exposure="experimental" },
    ["whitelist_actions"] = { method="POST", path="/whitelist/:table/:action", auth="apiAuthMw", exposure="experimental" },
    ["host_status"] = { method="GET", path="/host/status", auth="hostAuthMw", exposure="host-status" },
    ["dev_get"] = { method="GET", path="/dev/:scope", auth="none", exposure="blocked: development-only" },
    ["dev_post"] = { method="POST", path="/dev/:scope", auth="none", exposure="blocked: development-only" },
}
